version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.9"
  jobs:
    post_install:
      - pip install poetry
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

mkdocs:
   configuration: mkdocs.yml
