import datetime

from armis_sdk.entities.boundary import Boundary
from armis_sdk.entities.device import Device
from armis_sdk.entities.network_interface import NetworkInterface
from armis_sdk.entities.site import Site

ALL_DEVICE_FIELDS = [
    "boundaries",
    "brand",
    "category",
    "device_id",
    "display",
    "first_seen",
    "ipv4_addresses",
    "ipv6_addresses",
    "last_seen",
    "mac_addresses",
    "model",
    "names",
    "network_interfaces",
    "os_name",
    "os_version",
    "purdue_level",
    "risk_level",
    "serial_numbers",
    "site",
    "tags",
    "type",
    "visibility",
]
MOCK_DEVICE_PARTIAL = Device(
    custom={"MyField1": "foo", "MyField2": "bar"},
    brand="VMware",
    purdue_level=4.0,
)
MOCK_DEVICE_PARTIAL_RAW_DATA = {
    "brand": "VMware",
    "custom.MyField1": "foo",
    "custom.MyField2": "bar",
    "purdue_level": 4.0,
}
MOCK_DEVICE_FULL = Device(
    custom={},
    boundaries=[Boundary(id=1, name="Corporate")],
    brand="VMware",
    category="Computers",
    device_id=1,
    display="VMware",
    first_seen=datetime.datetime(2025, 5, 14, 8, 34, 10),
    ipv4_addresses=["10.246.212.12"],
    ipv6_addresses=["fe80::4d68:8d3e:d3a5:c930"],
    last_seen=datetime.datetime(2025, 12, 3, 13, 52, 45),
    mac_addresses=["43:87:a2:05:bc:56"],
    model="VMware",
    names=["VMware", "044D9BA4_B6E"],
    network_interfaces=[
        NetworkInterface(
            alias=None,
            brand=None,
            broadcast_ssid=None,
            channels=[],
            description=None,
            hidden_broadcast_ssid=None,
            ipv4_address=None,
            ipv6_address=None,
            last_connected_ssid=None,
            mac_address="43:87:a2:05:bc:56",
            name=None,
            type=None,
            vlan=1,
        )
    ],
    os_name="Windows",
    os_version="Server 2016",
    purdue_level=4.0,
    risk_level=80,
    serial_numbers=None,
    site=Site(
        id=36481,
        name="Geneva Enterprise",
        lat=None,
        lng=None,
        location="Geneva",
        parent_id=None,
        tier=None,
        asq_rule=None,
        network_equipment_device_ids=None,
        integration_ids=None,
        children=[],
    ),
    tags=[
        "Insecure Traffic and Behavior",
        "Critical Vulnerabilities",
        "Deprecated SW/HW",
        "Misconfigurations",
        "Unprotected Sensitive Data",
        "Insecure Credentials and Access Control",
    ],
    type="Virtual Machines",
    visibility="Full",
)
MOCK_DEVICE_FULL_RAW_DATA = {
    "boundaries": [{"id": 1, "name": "Corporate"}],
    "brand": "VMware",
    "category": "Computers",
    "device_id": 1,
    "display": "VMware",
    "first_seen": "2025-05-14T08:34:10",
    "ipv4_addresses": ["10.246.212.12"],
    "ipv6_addresses": ["fe80::4d68:8d3e:d3a5:c930"],
    "last_seen": "2025-12-03T13:52:45",
    "mac_addresses": ["43:87:a2:05:bc:56"],
    "model": "VMware",
    "names": ["VMware", "044D9BA4_B6E"],
    "network_interfaces": [
        {
            "alias": None,
            "brand": None,
            "broadcast_ssid": None,
            "channels": [],
            "description": None,
            "hidden_broadcast_ssid": None,
            "ipv4_address": None,
            "ipv6_address": None,
            "last_connected_ssid": None,
            "mac_address": "43:87:a2:05:bc:56",
            "name": None,
            "type": None,
            "vlan": 1,
        }
    ],
    "os_name": "Windows",
    "os_version": "Server 2016",
    "purdue_level": 4.0,
    "risk_level": 80,
    "serial_numbers": None,
    "site": {
        "id": 36481,
        "location": "Geneva",
        "name": "Geneva Enterprise",
        "tier": None,
    },
    "tags": [
        "Insecure Traffic and Behavior",
        "Critical Vulnerabilities",
        "Deprecated SW/HW",
        "Misconfigurations",
        "Unprotected Sensitive Data",
        "Insecure Credentials and Access Control",
    ],
    "type": "Virtual Machines",
    "visibility": "Full",
}
