# Based on https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
name: Publish to PyPI

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/armis_sdk
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/install_deps

      - name: Build
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
