# Based on https://github.com/marketplace/actions/python-poetry-action

name: Run tests

on:
  - push

permissions:
  contents: read

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/install_deps

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - name: Run tests
      run: poetry run pytest -vv

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - name: Run linter
      run: poetry run pylint ./**/*.py

  format:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - name: Run formatter
      run: poetry run black --check --diff .
