name: Run tests

on:
  - push

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/workflows/install_deps

    - name: Run tests
      run: poetry run pytest -vv
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/workflows/install_deps

    - name: Run mypy
      run: poetry run mypy .

